import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

const LABS = ["GuideLab", "ScaleLab", "PianoLab", "EarLab", "HarmonyLab", "RhythmLab", "JourneyLab", "RecordingLab", "AtlasLab", "PersonalLab"];

test("every learning lab exposes a named semantic region", async () => {
  for (const lab of LABS) {
    const source = await readFile(new URL(`../app/${lab}.tsx`, import.meta.url), "utf8");
    assert.match(source, /<section[^>]+aria-labelledby=/, `${lab} needs aria-labelledby`);
  }
});

test("dynamic visuals and status changes expose nonvisual descriptions", async () => {
  const [ratio, scale, piano, ear, harmony, rhythm, recording, journey, atlas, personal] = await Promise.all([
    readFile(new URL("../app/RatioLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/ScaleLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PianoLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/EarLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/HarmonyLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RhythmLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RecordingLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/JourneyLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/AtlasLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PersonalLab.tsx", import.meta.url), "utf8"),
  ]);
  assert.match(ratio, /<canvas[^>]+role="img"[^>]+aria-label=/);
  assert.match(scale, /name="scale-degree"/);
  assert.match(scale, /aria-live="polite"/);
  assert.match(scale, /<ol className="step-fingerprint"/);
  assert.match(piano, /aria-label="Silent two-octave on-screen piano/);
  assert.match(piano, /aria-live="polite"/);
  assert.match(piano, /Grand staff showing/);
  assert.match(piano, /Evidence traces across/);
  assert.match(piano, /Choose movable Do around the circle of fifths/);
  assert.match(piano, /Repeated fifths morphing from a nonclosing pure-ratio spiral/);
  assert.match(piano, /id="hud-fifths-stack"/);
  assert.match(piano, /id="hud-fifths-temper"/);
  assert.match(piano, /Select an event across every view/);
  assert.match(piano, /Chord gestures grouped by attack timing/);
  assert.match(piano, /aria-label="Selected chord evidence"/);
  assert.match(piano, /aria-label="Correct inherited chord membership"/);
  assert.match(piano, /Restore.*Exclude.*inherited/);
  assert.match(piano, /id="hud-chord-window"/);
  assert.match(piano, /aria-label="Guided ascending scale walk"/);
  assert.match(piano, /aria-label="Performed scale fingerprint builder"/);
  assert.match(piano, /aria-label="Scale landing mutation comparison"/);
  assert.match(piano, />Change one landing<\/button>/);
  assert.match(piano, /Change one landing, keep the octave/);
  assert.match(piano, /aria-label="Choose one consequence of the moved scale landing"/);
  assert.match(piano, />Every connected interval<\/button>/);
  assert.match(piano, /hud-scale-ripple-summary" role="img" aria-label=\{summary\}/);
  assert.match(piano, /Global consequence/);
  assert.match(piano, /hud-scale-ripple-reading" role="status" aria-live="polite"/);
  assert.match(piano, /aria-label="Assumed spectral consequence of one changed interval"/);
  assert.match(piano, /hud-scale-spectrum-summary" role="img" aria-label=\{summary\}/);
  assert.match(piano, /hud-scale-spectrum-reading" role="status" aria-live="polite"/);
  assert.match(piano, /MIDI contains no instrument spectrum/);
  assert.match(piano, /hud-scale-mutation-reading[\s\S]*role="status" aria-live="polite"/);
  assert.match(piano, /`Δ\$\{signed\(delta\)\}`/);
  assert.match(piano, /More than one landing moved, so no single-position explanation is justified/);
  assert.match(piano, /aria-label="Choose one scale experiment"/);
  assert.match(piano, /silent performed fingerprint target/);
  assert.match(piano, /aria-label="Tonal gravity counterfactual microscope"/);
  assert.match(piano, /aria-label="Counterfactual evidence separation"/);
  assert.match(piano, /aria-labelledby="hud-phrase-compare-entry-title"/);
  assert.match(piano, /aria-label="Choose one phrase change to investigate"/);
  assert.match(piano, /aria-label="Five separate phrase comparison lenses"/);
  assert.match(piano, /aria-labelledby="hud-partial-title"/);
  assert.match(piano, /role="img" aria-label=\{summary\}/);
  assert.match(piano, /role="img" aria-label=\{comparisonSummary\}/);
  assert.match(piano, /aria-label="Five separate lenses for the selected attack change"/);
  assert.match(piano, /hud-last-attack-reading[\s\S]*role="status" aria-live="polite"/);
  assert.match(piano, /hud-phrase-change-status" role="status" aria-live="polite"/);
  assert.match(piano, /aria-label="Ending relationship ripple"/);
  assert.match(piano, /hud-ending-ripple-summary" role="img" aria-label=\{summary\}/);
  assert.match(piano, /Trace every ending relationship/);
  assert.match(piano, /hud-ending-ripple-reading" role="status" aria-live="polite"/);
  assert.match(piano, /role="group" aria-label=\{row\.label\}/);
  assert.match(piano, /role="status" aria-live="polite"/);
  assert.match(piano, /silent guided scale-walk target/);
  assert.match(piano, /aria-labelledby="hud-sonority-title"/);
  assert.match(piano, /aria-label="Separate conditional affordance changes"/);
  assert.match(piano, /silent controlled sonority reference/);
  assert.match(piano, /aria-label="Original versus one-key path comparison across five lenses"/);
  assert.match(piano, /aria-label="Report which landmark path felt more directed"/);
  assert.match(piano, /aria-label="Motion learning question"/);
  assert.match(piano, /Show what survived/);
  assert.match(piano, /aria-controls="hud-motif-fingerprint-detail"/);
  assert.match(piano, /hud-motif-fingerprint-grid" role="img" aria-label=\{summary\}/);
  assert.match(piano, /Set each statement’s first key to 0/);
  assert.match(piano, /does not infer intended motif, formal function, emotion, quality, or correctness/);
  assert.match(piano, /aria-labelledby="hud-motif-echo-title"/);
  assert.match(piano, /aria-label="Choose motif source length"/);
  assert.match(piano, /Freeze last 3/);
  assert.match(piano, /No smaller sub-match can replace your chosen boundary/);
  assert.match(piano, /Every chosen attack entered this comparison/);
  assert.match(piano, /Local sequence · source → change → return/);
  assert.match(piano, /The variation is open—try bringing the relationship back/);
  assert.match(piano, /not a detected section, theme, compositional intention, style, listener recognition, or quality judgment/);
  assert.match(piano, /Did the last statement feel like a return to you\?/);
  assert.match(piano, /aria-label="Modeled relationship and listener report kept separate"/);
  assert.match(piano, /aria-label="Report whether the last statement felt like a return"/);
  assert.match(piano, /Agreement with the relationship detector is not a goal/);
  assert.match(piano, /Your report does not turn that relationship into detected form, universal recognition, emotion, correctness, or musical quality/);
  assert.match(piano, /Particular performances · no average/);
  assert.match(piano, /Did moving the relationship change your experience\?/);
  assert.match(piano, /They do not establish your recognition threshold or a general law about transposition/);
  assert.match(piano, />Reflect on the whole arc<\/button>/);
  assert.match(piano, /motifReturnArcEventIds\(session\.sourceEvents\.map/);
  assert.match(piano, /The source aged out of the sixty-second phrase\. Start a new arc to reflect on its exact timing/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("motif-return", specimen\)/);
  assert.match(piano, /prompt\s*\.replace\("this phrase", "this source–variation–return arc"\)/);
  assert.match(piano, /replace\("this relationship path", "this source–variation–return arc"\)/);
  assert.match(piano, /replace\("this particular experience", "this source–variation–return experience"\)/);
  assert.match(piano, /origin === "motif-return" \? "motif source \+ variation \+ return"/);
  assert.match(piano, /The exact source, latest variation, and relationship return are frozen together/);
  assert.match(piano, /Save this return-arc report/);
  assert.match(piano, />Reflect on performed path<\/button>/);
  assert.match(piano, /How did this whole performed route feel\?/);
  assert.match(piano, /landmarkPerformanceEventIds\(landmarkPerformanceCapture\.fieldEventIds, landmarkPath\.steps\.length\)/);
  assert.match(piano, /Every exact attack used to complete this generated path is frozen in its original chronology/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("landmark-path", specimen/);
  assert.match(piano, /Save this landmark-path report/);
  assert.match(piano, /this performed landmark path/);
  assert.match(personal, /Latest performed landmark:/);
  assert.match(piano, /aria-labelledby="hud-pulse-title"/);
  assert.match(piano, /Later MIDI attack clusters placed against the learner’s four-tap pulse/);
  assert.match(piano, /aria-labelledby="hud-phrase-breath-title"/);
  assert.match(piano, /Mark a candidate break after/);
  assert.match(piano, /Performed pitch path divided only at long onset-group gaps containing release-proven silence/);
  assert.match(piano, /hud-breath-reading" role="status" aria-live="polite"/);
  assert.match(piano, /Unknown releases, overlaps, and merely long held notes never become quiet-space boundaries/);
  assert.match(piano, /does not detect intended phrasing, breath, meter, form, expressiveness, correctness, or musical goodness/);
  assert.match(piano, />Compare one pause<\/button>/);
  assert.match(piano, /onComparePause=\{\(\) => beginPhraseCompare\("timing"\)\}/);
  assert.match(piano, /modeled crunch/);
  assert.match(piano, /MIDI contains no acoustic roughness measurement/);
  assert.match(ear, /aria-labelledby="live-ear-title"/);
  assert.match(ear, /role="img" aria-label=\{summary\}/);
  assert.match(ear, /aria-label="Five separate lenses for this interval and its assumed sounds"/);
  assert.match(ear, /<details className="ear-authoring-disclosure"/);
  assert.match(harmony, /aria-labelledby="live-harmony-title"/);
  assert.match(harmony, /role="img" aria-label=\{accessibleSummary\}/);
  assert.match(harmony, /aria-label="Five separate evidence lenses for the chord change"/);
  assert.match(harmony, /<details className="harmony-authoring-disclosure"/);
  assert.match(rhythm, /aria-labelledby="rhythm-live-title"/);
  assert.match(rhythm, /role="img"/);
  assert.match(rhythm, /Pitchless timing profile with/);
  assert.match(rhythm, /<details className="rhythm-authoring-disclosure"/);
  assert.match(recording, /aria-live="polite"/);
  assert.match(journey, /role="img" aria-label=/);
  assert.match(journey, /aria-labelledby="journey-live-title"/);
  assert.match(journey, /Piece-local expectation trail/);
  assert.match(journey, /<details className="journey-generated-disclosure"/);
  assert.match(atlas, /aria-label=\{`Music landmarks positioned/);
});

test("focus, reduced-motion, and non-color contracts are present", async () => {
  const [css, ratio, scale, piano, ear, harmony, rhythm, journey] = await Promise.all([
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/RatioLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/ScaleLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PianoLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/EarLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/HarmonyLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RhythmLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/JourneyLab.tsx", import.meta.url), "utf8"),
  ]);
  assert.match(css, /select:focus-visible/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
  assert.match(css, /animation-duration: 0\.01ms !important/);
  assert.match(css, /cloud-blues[\s\S]*border-style: dotted/);
  assert.match(css, /cloud-classical[\s\S]*border-style: double/);
  assert.match(css, /\.atlas-point[\s\S]*width: max\(50px, var\(--point-size\)\)/);
  assert.match(css, /\.lab-nav-primary[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(ratio, /<details className="lab-nav-more"/);
  assert.match(ratio, /aria-label="Live piano phrase available"/);
  assert.match(ratio, /matchMedia\("\(prefers-reduced-motion: reduce\)"\)/);
  assert.match(ratio, /behavior: prefersReducedMotion \? "auto" : "smooth"/);
  assert.match(ratio, /className="skip-link" href="#lab-stage" onClick=\{skipToActiveLab\}/);
  assert.match(ratio, /id="lab-stage" className="lab-stage" tabIndex=\{-1\}/);
  assert.match(css, /@media \(forced-colors: active\)/);
  assert.match(css, /\.atlas-point\.is-selected > i[\s\S]*outline: 4px solid Highlight/);
  assert.match(css, /\.spectrum-partial\.voice-6[\s\S]*border: 3px double Canvas/);
  assert.match(css, /\.learning-scale \.step-fingerprint > li span/);
  assert.doesNotMatch(ratio, /tabIndex=\{?[1-9]/);
  assert.doesNotMatch(scale, /className="degree-inspector"[^>]*aria-live/);
  assert.doesNotMatch(piano, /tabIndex=\{?[1-9]/);
  assert.match(css, /\.piano-key\.is-circle-target/);
  assert.match(css, /\.piano-key\.is-scale-walk-target/);
  assert.match(css, /\.piano-key\.is-scale-builder-target/);
  assert.match(css, /\.hud-gravity-counterfactual-chart > span\.is-target/);
  assert.match(css, /\.hud-gravity-counterfactual-chart i\.is-before[\s\S]*LinkText/);
  assert.match(css, /\.hud-phrase-lens-profile > article\.is-invariant[\s\S]*border-left/);
  assert.match(css, /\.hud-phrase-change-reading\.has-target[\s\S]*LinkText/);
  assert.match(css, /\.hud-phrase-change-reading > button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-ending-ripple-spoke \.is-attempt i b[\s\S]*border: 1px dashed/);
  assert.match(css, /\.hud-ending-ripple-reading \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-motif-fingerprint-entry button\[aria-expanded="true"\]/);
  assert.match(css, /\.hud-motif-time-bar i[\s\S]*flex: var\(--motif-gap-share\)/);
  assert.match(css, /\.hud-motif-fingerprint-grid \{ grid-template-columns: minmax\(76px/);
  assert.match(css, /\.hud-motif-echo-start \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-return-trail ol \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-return-trail li\.is-variation[\s\S]*border-top-style: dashed/);
  assert.match(css, /\.hud-motif-return-trail li\.is-return[\s\S]*border-top-style: double/);
  assert.match(css, /\.hud-motif-return-trail li\.is-return \{ border-top-color: LinkText/);
  assert.match(css, /\.hud-motif-experience-options button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-motif-experience-options \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-experience-options button\[aria-pressed="true"\][\s\S]*HighlightText/);
  assert.match(css, /\.hud-motif-return-contrast li\.is-shifted[\s\S]*border-top-style: dashed/);
  assert.match(css, /\.hud-motif-return-contrast ol \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-return-contrast li\.is-shifted \{ border-top-color: LinkText/);
  assert.match(css, /\.hud-motif-echo button \{ color: ButtonText/);
  assert.match(css, /\.hud-partial-link\.is-aligned[\s\S]*LinkText/);
  assert.match(css, /\.hud-partial-link\.is-interaction[\s\S]*Highlight/);
  assert.match(css, /\.hud-echo-span\.is-source[\s\S]*LinkText/);
  assert.match(css, /\.hud-echo-span\.is-attempt[\s\S]*Highlight/);
  assert.match(css, /\.hud-scale-mutation-routes \.is-source \.is-present i[\s\S]*border-radius: 50%/);
  assert.match(css, /\.hud-scale-mutation-routes \.is-attempt \.is-present i[\s\S]*border-style: dashed/);
  assert.match(css, /\.hud-scale-mutation-routes \.is-present\.is-changed i[\s\S]*border: 3px double/);
  assert.match(css, /\.hud-scale-mutation-gaps \{ grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.hud-scale-mutation-reading \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-scale-mutation-view button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-scale-ripple-spoke \.is-attempt i b[\s\S]*border: 1px dashed/);
  assert.match(css, /\.hud-scale-ripple-spoke \.is-attempt i b[\s\S]*border-color: Highlight/);
  assert.match(css, /\.hud-scale-ripple-reading \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-scale-ripple-spoke\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-scale-spectrum-partial\.is-upper[\s\S]*stroke-dasharray/);
  assert.match(css, /\.hud-scale-spectrum-interaction[\s\S]*fill: var\(--piano-gold\)/);
  assert.match(css, /\.hud-scale-spectrum-reading \{ border-left-color: LinkText/);
  assert.match(piano, /aria-label="Interval context lesson"/);
  assert.match(piano, /aria-label="Five separate lenses for the source and echoed interval"/);
  assert.match(piano, />Reflect on source \+ echo<\/button>/);
  assert.match(piano, /origin === "interval-echo" \? "interval source \+ echo"/);
  assert.match(piano, /replace\("this phrase", "this source-and-echo comparison"\)/);
  assert.match(piano, /"Use whole live phrase"/);
  assert.match(piano, /aria-label="Five separate lenses for the selected chord change"/);
  assert.match(piano, />Reflect on chord change<\/button>/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("chord-change", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this chord change"\)/);
  assert.match(piano, /aria-label="Choose one chord-learning question"/);
  assert.match(piano, /aria-label="Five separate lenses for the source chord and new voicing"/);
  assert.match(piano, /<svg className="hud-chord-echo-figure"[\s\S]*role="img"/);
  assert.match(piano, />Freeze this relationship<\/button>/);
  assert.match(piano, />Reflect on source \+ voicing<\/button>/);
  assert.match(piano, /What remains if register, doubling, and starting pitch disappear\?/);
  assert.match(piano, /Fold into one octave/);
  assert.match(piano, /How did changing one position reshape the chord\?/);
  assert.match(piano, /Compare changed gaps/);
  assert.match(piano, /Delta labels show exactly which adjacent gaps gained or lost space/);
  assert.match(piano, /both closed loops still total 12/);
  assert.match(piano, /aria-pressed=\{octaveFoldRevealed\}/);
  assert.match(piano, /<svg className="hud-chord-fold-figure"[\s\S]*role="img"/);
  assert.match(piano, /comparison start is a canonical rotation, not a chord root or movable Do/);
  assert.match(piano, /This display-only view changes no MIDI, frequency, voicing, model, or listener report/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("chord-voicing-echo", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this source-and-revoicing comparison"\)/);
  assert.match(piano, /sourceEvents: saved\.chordVoicingEchoSession\.sourceEvents\.map/);
  assert.match(piano, /aria-label="Five separate lenses for the source and replayed chord move"/);
  assert.match(piano, /<svg className="hud-chord-motion-figure"[\s\S]*role="img"/);
  assert.match(piano, />Freeze this two-chord move<\/button>/);
  assert.match(piano, />Reflect on source \+ replayed move<\/button>/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("chord-motion-echo", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this source-and-replayed chord move"\)/);
  assert.match(piano, /sourceBeforeEvents: saved\.chordMotionEchoSession\.sourceBeforeEvents\.map/);
  assert.match(piano, /aria-label="Choose the replay's movable Do reference frame"/);
  assert.match(piano, />Does the tonal job travel when the reference frame travels\?</);
  assert.match(piano, />Keep Do fixed<\/button>/);
  assert.match(piano, />Move Do \{signed\(comparison\.transpositionSteps!\)\}<\/button>/);
  assert.match(piano, /This is a display-only context counterfactual and never enters or sounds a note/);
  assert.match(piano, /replay Do moved \+ same route/);
  assert.match(piano, /restored the same relative-role path under this model; it did not prove the same heard function/);
  assert.match(piano, /The display-only Do counterfactual never supplies your report/);
  assert.match(piano, />What did this intended landing actually do\?</);
  assert.match(piano, /"Trace this landing"/);
  assert.match(piano, /aria-expanded=\{landingRevealed\}/);
  assert.match(piano, /aria-controls="hud-resolution-landing-panel"/);
  assert.match(piano, /<p className="sr-only" role="status" aria-live="polite">\{targetMatched/);
  assert.match(piano, /aria-label="Five separate lenses for the performed resolution landing"/);
  assert.match(piano, /The fork label named an intention, not a detected function or felt resolution/);
  assert.match(piano, /No lens proves that the fork resolved, caused a feeling, was stylistically correct, or was musically good/);
  assert.match(piano, /Pull is modeled distance still left before Do, so zero can mean arrival—not indifference/);
  assert.match(piano, /sourceEvent: \{ \.\.\.sourceEvent, fieldNotes: \[\.\.\.sourceEvent\.fieldNotes\] \}/);
  assert.match(piano, /!phraseEvents\.some\(\(event\) => event\.id === resolutionTarget\.sourceEvent!/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("resolution-fork", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this intended landing in context"\)/);
  assert.match(piano, /aria-label="One-pause timing comparison"/);
  assert.match(piano, /Two performances of the same pitch path with one onset gap changed/);
  assert.match(piano, /hud-pause-reading" role="status" aria-live="polite"/);
  assert.match(piano, /"Trace the changed pause"/);
  assert.match(piano, /aria-expanded=\{pauseRevealed\}/);
  assert.match(piano, /aria-controls="hud-pause-mutation-detail"/);
  assert.match(piano, /Onset spacing and release-proven silence are separate/);
  assert.match(piano, /does not prove a phrase boundary, meter, expressive intention, emotion, preference, quality, or causal effect/);
  assert.match(piano, />Did the hands make the same time-shape\?</);
  assert.match(piano, /"Compare gesture timing"/);
  assert.match(piano, /aria-expanded=\{gestureTimingRevealed\}/);
  assert.match(piano, /aria-controls="hud-chord-gesture-detail"/);
  assert.match(piano, /<svg viewBox="0 0 720 150" role="img"/);
  assert.match(piano, /Missing releases remain unknown\. Velocity is an attack control, not measured acoustic loudness/);
  assert.match(piano, /does not infer meter, groove, intention, feeling, preference, or quality/);
  assert.match(piano, /sourceBeforeAttackEventIds: before\.gesture\.attacks\.map/);
  assert.match(piano, /version: 24/);
  assert.match(piano, /experienceOrigin === "phrase" \|\| experiencePhrase\.length < 3/);
  assert.match(piano, /landmarkLastMatchIdRef\.current = 0;\s+setExperienceOrigin\("phrase"\);\s+setExperienceContext\(null\);\s+setExperiencePhrase\(\[\]\);/);
  assert.match(piano, /<details className="hud-interval-tools">/);
  assert.match(piano, /simultaneous partial-interaction comparison would answer the wrong question/);
  assert.match(css, /\.hud-echo-reading[\s\S]*grid-template-columns: repeat\(3/);
  assert.match(css, /\.hud-echo-experience button \{ justify-self: start/);
  assert.match(css, /\.hud-chord-change-lenses,[\s\S]*\.hud-chord-echo,[\s\S]*\.hud-chord-motion-echo \{ min-width: 0/);
  assert.match(css, /\.hud-chord-question-options button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-chord-echo-node\.is-source[\s\S]*LinkText/);
  assert.match(css, /\.hud-chord-fold-test > button\[aria-pressed="true"\][\s\S]*background: var\(--foreground\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-fold-test > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-fold-figure \.is-attempt \.hud-chord-fold-node[\s\S]*HighlightText/);
  assert.match(css, /\.hud-chord-fold-segment\.is-changed[\s\S]*stroke-dasharray: 2 2/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-fold-segment\.is-changed \{ stroke: Highlight/);
  assert.match(css, /\.hud-chord-motion-node\.is-source\.is-before[\s\S]*CanvasText/);
  assert.match(css, /\.hud-chord-motion-node\.is-attempt\.is-after[\s\S]*HighlightText/);
  assert.match(css, /\.hud-resolution-landing-node\.is-landing rect[\s\S]*var\(--piano-gold\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-resolution-feedback-actions button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-resolution-landing-node\.is-landing rect \{ fill: Highlight/);
  assert.match(css, /\.hud-pause-link \.is-attempt \{ stroke-dasharray/);
  assert.match(css, /\.hud-pause-link\.is-changed line[\s\S]*var\(--piano-gold\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-pause-entry > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-pause-link\.is-changed line,[\s\S]*stroke: Highlight/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-pause-node\.is-attempt rect \{ stroke: LinkText/);
  assert.match(css, /\.hud-chord-gesture-test > button\[aria-expanded="true"\]/);
  assert.match(css, /\.hud-chord-gesture-hold\.is-pedal[\s\S]*stroke-dasharray/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-gesture-test > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-gesture-attack\.is-after \{ fill: Highlight/);
  assert.match(css, /\.hud-chord-frame-options button\[aria-pressed="true"\][\s\S]*background: var\(--foreground\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-question-options \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-motion-actions button \{ width: 100%/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-frame-options \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-frame-options button\[aria-pressed="true"\][\s\S]*background: Highlight/);
  assert.match(css, /\.hud-last-lenses button:disabled/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-echo-reading \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-last-attack-reading\.is-attributable[\s\S]*LinkText/);
  assert.match(css, /\.hud-last-lenses article\.is-modeled[\s\S]*Highlight/);
  assert.match(css, /\.hud-phrase-report-rows button\[aria-pressed="true"\][\s\S]*Highlight/);
  assert.match(css, /\.hud-landmark-counterfactual-report button\[aria-pressed="true"\][\s\S]*Highlight/);
  assert.match(css, /\.piano-key\.is-sonority-target/);
  assert.match(css, /\.hud-sonority-question\.has-change[\s\S]*border-left/);
  assert.match(css, /\.hud-pulse-status\.is-ready[\s\S]*border-left/);
  assert.match(css, /\.hud-pulse-onset[\s\S]*Highlight/);
  assert.match(css, /\.hud-breath-gate line[\s\S]*stroke-dasharray/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-motion-mode-nav button:last-child \{ grid-column: 1 \/ -1/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-breath-segments \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-breath-gate line \{ stroke: Highlight/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-breath-event circle \{ fill: Canvas; stroke: CanvasText/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-breath-next > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-breath-next \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-walk-route li\.is-current[\s\S]*box-shadow/);
  assert.match(css, /\.piano-key\.is-active,[\s\S]*Highlight/);
  assert.match(css, /\.rhythm-live-axis > span[\s\S]*background: LinkText/);
  assert.doesNotMatch(rhythm, /tabIndex=\{?[1-9]/);
  assert.match(css, /\.journey-live-thread > li\.is-known[\s\S]*border-color: LinkText/);
  assert.match(css, /\.journey-live-thread > li\.is-new[\s\S]*border-color: Highlight/);
  assert.match(css, /\.live-harmony-note\.is-previous[\s\S]*stroke: LinkText/);
  assert.match(css, /\.live-harmony-note\.is-current[\s\S]*fill: Highlight/);
  assert.match(css, /\.live-ear-roughness circle[\s\S]*stroke: Highlight/);
  assert.match(css, /\.live-ear-harmonicity rect[\s\S]*stroke: LinkText/);
  assert.match(css, /\.live-ear-fusion path[\s\S]*fill: Highlight/);
  assert.doesNotMatch(ear, /tabIndex=\{?[1-9]/);
  assert.doesNotMatch(harmony, /tabIndex=\{?[1-9]/);
  assert.doesNotMatch(journey, /tabIndex=\{?[1-9]/);
});
