import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

const LABS = ["GuideLab", "ScaleLab", "PianoLab", "VoiceLab", "EarLab", "HarmonyLab", "RhythmLab", "JourneyLab", "RecordingLab", "AtlasLab", "PersonalLab"];

test("every learning lab exposes a named semantic region", async () => {
  for (const lab of LABS) {
    const source = await readFile(new URL(`../app/${lab}.tsx`, import.meta.url), "utf8");
    assert.match(source, /<section[^>]+aria-labelledby=/, `${lab} needs aria-labelledby`);
  }
});

test("immersive, research, and scale-gravity piano HUDs plus vocal pitch match keep visual channels named, bounded, and non-color-only", async () => {
  const [piano, immersion, research, gravity, voiceLab, vocal, model, researchModel, gravityModel, vocalModel, vocalSpectrumModel, css] = await Promise.all([
    readFile(new URL("../app/PianoLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PianoImmersion.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PianoResearchHud.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PianoScaleGravityHud.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/VoiceLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/VocalPitchCoach.tsx", import.meta.url), "utf8"),
    readFile(new URL("../lib/piano-immersion-model.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/piano-research-model.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/piano-scale-gravity-model.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/vocal-pitch-model.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/vocal-spectrum-model.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(piano, /focusLens === "immersion" \? <PianoImmersion/);
  assert.match(piano, /focusLens === "research" \? <PianoResearchHud/);
  assert.match(piano, /focusLens === "gravity" \? <PianoScaleGravityHud/);
  assert.match(piano, /events=\{immersionHistoryEvents\}/);
  assert.match(piano, /const isShortHudFocus = focusLens === "immersion" \|\| focusLens === "research" \|\| focusLens === "gravity"/);
  assert.match(piano, /pulseMirror=\{pulseMirrorModel\}/);
  assert.match(piano, /<details className="piano-immersion-keyboard">/);
  assert.doesNotMatch(piano, /VocalPitchCoach/);
  assert.match(piano, /Sung-pitch practice now lives on the dedicated Voice page/);
  assert.match(voiceLab, /<VocalPitchCoach/);
  assert.match(voiceLab, /anchorSource="voice-lab-reference"/);
  assert.match(voiceLab, /id="voice-anchor-key"/);
  assert.match(voiceLab, /estimates sung pitch only—it does not recognize words/);
  assert.match(piano, /<RouteSelector scale=\{scale\}/);
  assert.match(piano, /doCaptureArmed=\{doCaptureArmed\}/);
  assert.match(piano, /onToggleDoCapture=\{toggleDoCapture\}/);
  assert.match(piano, /frameLearningActive=\{frameMode === "discover" && frameLearningAnchorId != null\}/);
  assert.match(piano, /frameLearningDistinctPitchClasses=\{frameLearningDistinctPitchClasses\}/);
  assert.match(piano, /onResetFrameFromPlaying=\{resetFrameFromPlaying\}/);
  assert.match(piano, /const resetFrameFromPlaying = \(\) =>/);
  assert.match(piano, /frameLearningAnchorIdRef\.current = anchorId/);
  assert.match(piano, /phraseEvents\.filter\(\(event\) => event\.id > frameLearningAnchorId\)/);
  assert.match(piano, /url\.searchParams\.delete\("pianoDo"\)/);
  assert.match(piano, /url\.searchParams\.delete\("pianoScale"\)/);
  assert.match(piano, /id="piano-route-choice"/);
  assert.match(piano, /Set Do from next note/);
  assert.match(piano, /Cancel · waiting for Do/);
  assert.match(piano, /Play one new MIDI or on-screen attack/);
  assert.match(piano, /Available in every Piano focus/);
  assert.match(piano, /function RouteSelector\(\{ scale, doMidi, frameMode, showConventions, doCaptureArmed/);
  assert.match(piano, /const captureArmedDoAttack = useCallback/);
  assert.match(piano, /captureArmedDoAttack\(note\);[\s\S]*addEvent\(note, velocity/);
  assert.match(piano, /captureArmedDoAttack\(note\);[\s\S]*addEvent\(note, 104/);
  assert.match(piano, /url\.searchParams\.set\("pianoDo", String\(pitchClass\)\)/);
  assert.match(piano, /How to select a route/);
  assert.match(piano, /Play while discovering/);
  assert.match(piano, /Adopt a candidate/);
  assert.match(piano, /The fifths compass changes Do while retaining the selected route/);
  assert.match(piano, /const selectScaleRoute/);
  assert.doesNotMatch(piano, /immersionChordGestures\.slice\(-5\)/);
  assert.match(piano, /const immersionHistoryEvents = useMemo\(\(\) => immersionHistory\(phraseEvents\)/);
  assert.match(piano, /groupChordGestures\(immersionHistoryEvents[\s\S]*measureChordGestures\(immersionChordGestures[\s\S]*IMMERSION_MAX_FIELD_NOTES\)\.slice\(-4\)/);
  assert.match(piano, /phraseEvents=\{immersionHistoryEvents\}/);
  assert.match(piano, /shared HUD history · notes \+ chords/);
  assert.match(piano, /if \(!isShortHudFocus\)[\s\S]*window\.setInterval\(\(\) => setNowMs\(currentHudTime\(\)\), 120\)/);
  assert.match(piano, /window\.setTimeout\(\(\) => setNowMs\(currentHudTime\(\)\), remainingMs\)/);
  assert.match(immersion, /<section className="piano-immersion" aria-labelledby="piano-immersion-title">/);
  assert.match(immersion, /role="img" aria-labelledby="piano-immersion-svg-title piano-immersion-svg-description"/);
  assert.match(immersion, /<desc id="piano-immersion-svg-description">\{visualSummary\}<\/desc>/);
  assert.match(immersion, /role="status" aria-live="polite" aria-atomic="true"/);
  assert.match(immersion, /window\.setTimeout\(\(\) => setAnnouncedSummary\(liveSummary\), 280\)/);
  assert.match(immersion, /className="piano-immersion-edge-hud"/);
  assert.match(immersion, /className="piano-immersion-lens is-scale"/);
  assert.match(immersion, /className="piano-immersion-scale-grid" role="img" aria-label=\{scaleLensSummary\}/);
  assert.match(immersion, /Array\.from\(\{ length: 12 \}/);
  assert.match(immersion, /each cell = 1 semitone/);
  assert.match(immersion, /Filled cell = selected route degree · dot = recent five-attack position · double dot = latest · outline = sounding/);
  assert.match(immersion, /This is the chosen scale coordinate, not a detected key/);
  assert.match(immersion, /aria-label="Quick scale-frame controls"/);
  assert.match(immersion, /Reset Do · next note/);
  assert.match(immersion, /Reset frame · play scale/);
  assert.match(immersion, /role="status" aria-live="polite"/);
  assert.match(immersion, /the next new MIDI or on-screen note becomes Do/);
  assert.match(immersion, /distinct notes since reset/);
  assert.match(immersion, /className="piano-immersion-lens is-rhythm" aria-labelledby=/);
  assert.match(immersion, /className="piano-immersion-lens is-harmony" aria-labelledby=/);
  assert.match(immersion, /className="piano-immersion-lens is-melody" aria-labelledby=/);
  assert.match(immersion, /piano-immersion-latest-transition[\s\S]*role="group" aria-label=\{latestTransitionSummary\}/);
  assert.match(immersion, /className="piano-immersion-interval-context-bar" aria-labelledby=/);
  assert.match(immersion, /Latest sequential key interval/);
  assert.match(immersion, /exact attack-to-attack MIDI-key differences/);
  assert.match(immersion, /exact chronological attack spacing, not an isolated melody interval/);
  assert.match(immersion, /not whole-field voice leading/);
  assert.match(immersion, /simultaneous roughness withheld/);
  assert.match(immersion, /Prompts, not a prediction of emotion, consonance, preference, or meaning/);
  assert.match(immersion, /viewBox="0 0 112 112" role="img" aria-label=\{ringSummary\}/);
  assert.match(immersion, /Local onset ruler · not a beat/);
  assert.match(immersion, /Grid distance is descriptive—not timing accuracy, groove quality, or inferred meter/);
  assert.match(immersion, /aria-label="Declared meter and metronome controls"/);
  assert.match(immersion, /Lock meter now/);
  assert.match(immersion, /Unlock meter/);
  assert.match(immersion, /Start metronome/);
  assert.match(immersion, /className=\{`piano-immersion-rhythm-track/);
  assert.match(immersion, /Lock captures the downbeat you supplied/);
  assert.match(immersion, /Change cues · no resolution verdict/);
  assert.match(immersion, /listener only · unreported/);
  assert.match(immersion, /Scale frames this five-note span may fit/);
  assert.match(immersion, /compatible pitch containers, not proof of key, origin, harmony, or intention/);
  assert.match(immersion, />Current chord</);
  assert.match(immersion, /Exact catalog name/);
  assert.match(immersion, /Exact catalog name · inversion/);
  assert.match(immersion, /function chordInversionLabel/);
  assert.match(immersion, /first inversion/);
  assert.match(immersion, /is the bass over/);
  assert.match(immersion, /is both root and bass · root position/);
  assert.match(immersion, /function ChordFingeringGraphic/);
  assert.match(immersion, /Suggested \{handLabel\} hand/);
  assert.match(immersion, /voicing center below middle C/);
  assert.match(immersion, /voicing center at or above middle C/);
  assert.match(immersion, /1 thumb · 5 pinky/);
  assert.match(immersion, /One common \$\{handLabel\}-hand fingering for/);
  assert.match(immersion, /center below middle C suggests left hand/);
  assert.match(immersion, /center at or above it suggests right/);
  assert.match(immersion, /Hand size, black keys, crossing, accompaniment, and the next chord may favor another choice/);
  assert.match(immersion, /function ScaleFingeringCue/);
  assert.match(immersion, /Suggested \{handLabel\} hand · ascending/);
  assert.match(immersion, /role="img"[\s\S]*Suggested \$\{handLabel\}-hand ascending octave fingering/);
  assert.match(immersion, /octave centered below middle C/);
  assert.match(immersion, /octave centered at or above middle C/);
  assert.match(immersion, /thumb under after route degree/);
  assert.match(immersion, /black-key layout, direction, hand size, and the surrounding passage can favor another fingering/);
  assert.match(immersion, /melody and accompaniment are not isolated/);
  assert.match(immersion, /planImmersionAnnotations\(annotationInputs, 1/);
  assert.match(immersion, /<select id="immersion-sound-model"/);
  assert.match(immersion, /dash density shows 12-TET mismatch to the named reference/);
  assert.match(immersion, /long dash = incomplete catalog fit · dotted overtrace = rolled timing/);
  assert.match(immersion, /broken wake needs release-proven silence/);
  assert.match(immersion, /These channels are never collapsed into correctness, emotion, preference, or musical goodness/);
  assert.match(immersion, /latest attack-time snapshot/);
  assert.match(immersion, /<details className="piano-immersion-guide">/);
  assert.match(immersion, /preserveAspectRatio="xMidYMid slice"/);
  assert.match(immersion, /Pitch bend, keyboard or DAW tuning, acoustic pitch, audio spectrum, and acoustic loudness are not captured/);
  assert.match(immersion, /modeled crunch pauses above/);
  assert.match(immersion, /Semitone horizon\. Octave-folded field pair counts/);
  assert.match(immersion, /selected-Do pull heuristic/);
  assert.match(immersion, /contextual, not a physical force or felt-resolution prediction/);
  assert.match(immersion, /aria-label="Persistent circle-of-fifths visual key"/);
  assert.match(immersion, /One fifths crown/);
  assert.match(immersion, /no attack-density bars/);
  assert.match(immersion, /Attack circle/);
  assert.doesNotMatch(immersion, /feGaussianBlur|<filter /);
  assert.doesNotMatch(immersion, /tabIndex=\{?[1-9]/);
  assert.match(research, /<section className="piano-research-hud" aria-labelledby="piano-research-title">/);
  assert.match(research, /aria-label="Research HUD note arrangement"/);
  assert.match(research, /aria-pressed=\{layout === option\.id\}/);
  assert.match(research, /id="piano-research-generator"/);
  assert.match(research, /role="img" aria-labelledby="piano-research-clock-title piano-research-clock-description"/);
  assert.match(research, /<desc id="piano-research-clock-description">\{clockSummary\}<\/desc>/);
  assert.match(research, /one neighboring position is one semitone/);
  assert.match(research, /Do = \{doLabel\}/);
  assert.match(research, /const anchorNote = doMidi;/);
  assert.doesNotMatch(research, /const anchorNote = latest\?\.note \?\? doMidi/);
  assert.match(research, /Loop length = 12 ÷ gcd\(12, \{generator\.step\}\)/);
  assert.match(research, /className="piano-research-lattice" role="list"/);
  assert.match(research, /className=\{classes\} role="listitem"/);
  assert.match(research, /→ \+3 st · minor third/);
  assert.match(research, /↓ \+4 st · major third/);
  assert.match(research, /↘ \+7 st · perfect fifth/);
  assert.match(research, /major-triad pitch-class shape uses the anchor, one step down \(\+4\), and one step down-right \(\+7\)/);
  assert.match(research, /minor-triad shape uses the anchor, one step right \(\+3\)/);
  assert.match(research, /<div className="piano-research-matrix-layout">/);
  assert.doesNotMatch(research, /className="piano-research-matrix-layout" role="img"/);
  assert.match(research, /<table className="piano-research-matrix" aria-describedby="piano-research-matrix-reading">/);
  assert.match(research, /Latest sequential movement/);
  assert.match(research, /exact attack-to-attack MIDI-key distance/);
  assert.match(research, /fifth steps, not generic note affinity, consonance, harmonic function, resolution, emotion, or quality/);
  assert.match(research, /pure 3:2 fifths do not close exactly after twelve steps/);
  assert.match(research, /do not measure acoustic pitch, piano tuning, overtones, loudness, or listening experience/);
  assert.doesNotMatch(research, /tabIndex=\{?[1-9]/);
  assert.match(gravity, /<section className="piano-scale-gravity-hud" aria-labelledby="piano-scale-gravity-title">/);
  assert.match(gravity, /A composer’s choir warm-up becomes a live map/);
  assert.match(gravity, /className="piano-scale-gravity-slots" role="group"/);
  assert.match(gravity, /Array\.from\(\{ length: 13 \}/);
  assert.match(gravity, /className="piano-scale-gravity-degree-picker" role="group"/);
  assert.match(gravity, /aria-pressed=\{pinnedDegree === node\.degree\}/);
  assert.match(gravity, /This runway is an exact physical window from selected Do to Do′/);
  assert.match(gravity, /latestWindowOffset === offset/);
  assert.match(gravity, /latest captured field matched/);
  assert.match(gravity, /Equally nearest triad tones/);
  assert.match(gravity, /className="piano-scale-gravity-contexts" role="group"/);
  assert.match(gravity, /Exact structure/);
  assert.match(gravity, /Style-bound tendency/);
  assert.match(gravity, /Listening prompt/);
  assert.match(gravity, /id="piano-scale-gravity-mode-home"/);
  assert.match(gravity, /This moves a listening frame, not the pitches or the app’s selected Do/);
  assert.match(gravity, /not the basis of all music/);
  assert.match(gravity, /Natural minor is its sixth rotation/);
  assert.match(gravity, /floating or pastel[\s\S]*listening prompt/);
  assert.doesNotMatch(gravity, /tabIndex=\{?[1-9]/);
  assert.match(gravityModel, /MAJOR_SCALE_OFFSETS = \[0, 2, 4, 5, 7, 9, 11\]/);
  assert.match(gravityModel, /MAJOR_SCALE_STEPS = \[2, 2, 1, 2, 2, 2, 1\]/);
  assert.match(gravityModel, /export function majorDegreeHarmonyReading/);
  assert.match(gravityModel, /export function physicalScaleGravityWindowOffset/);
  assert.match(gravityModel, /export function recognizeMajorHarmonyContext/);
  assert.match(gravityModel, /export function rotateMajorMode/);
  assert.match(css, /\.piano-scale-gravity-slots[\s\S]*grid-template-columns: repeat\(13, minmax\(0, 1fr\)\)/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.piano-scale-gravity-intro/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-scale-gravity-slots/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-scale-gravity-degree-picker[\s\S]*repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-scale-gravity-hud/);
  assert.match(css, /\.piano-focus-lenses[\s\S]*repeat\(10, minmax\(0, 1fr\)\)/);
  assert.match(model, /IMMERSION_HISTORY_ATTACKS = 12/);
  assert.match(model, /export function immersionHistory[\s\S]*slice\(-IMMERSION_HISTORY_ATTACKS\)/);
  assert.match(model, /IMMERSION_MAX_FIELD_NOTES = 8/);
  assert.match(model, /IMMERSION_MAX_INTERVAL_LINKS = 12/);
  assert.match(model, /IMMERSION_MAX_ANNOTATIONS = 5/);
  assert.match(model, /export function immersionRhythmLens/);
  assert.match(model, /export function immersionMeterGrid/);
  assert.match(model, /learner-declared meter/);
  assert.match(model, /fallback ruler is deliberately not promoted to a beat, meter, or accuracy/);
  assert.match(model, /export function immersionIntervalCharacter/);
  assert.match(model, /export function immersionLatestTransition/);
  assert.match(model, /directionalFrequencyRatio: 2 \*\* \(signedSemitones \/ 12\)/);
  assert.match(model, /snapshotOverlap[\s\S]*from\.note !== to\.note/);
  assert.match(model, /export function immersionRecentPath/);
  assert.match(model, /Catalog results are compatibility[\s\S]*matches over pitch classes/);
  assert.match(researchModel, /export function chromaticClock/);
  assert.match(researchModel, /export function generatorComponents/);
  assert.match(researchModel, /const divisor = greatestCommonDivisor\(step, RESEARCH_PITCH_CLASS_COUNT\)/);
  assert.match(researchModel, /export function thirdsLattice/);
  assert.match(researchModel, /3 \* x \+ 4 \* y/);
  assert.match(researchModel, /export function intervalMatrix/);
  assert.match(vocal, /id="voice-interval"/);
  assert.match(vocal, /id="voice-input-level"/);
  assert.match(vocal, /id="voice-input-source"/);
  assert.match(vocal, /Microphone source/);
  assert.match(vocal, /System default/);
  assert.match(vocal, /enumerateDevices/);
  assert.match(vocal, /deviceId: \{ exact: microphoneId \}/);
  assert.match(vocal, /addEventListener\("devicechange"/);
  assert.match(vocal, /Microphone input activity/);
  assert.match(vocal, /voice is very quiet · move closer/);
  assert.match(vocal, /voice heard · hold one vowel steady/);
  assert.match(vocal, /pitch detected/);
  assert.match(vocal, /activeInputLabel/);
  assert.match(vocalModel, /VOCAL_INPUT_MINIMUM_RMS = 0\.0015/);
  assert.match(vocal, /Start microphone/);
  assert.match(vocal, /Stop microphone/);
  assert.match(vocal, /Hear anchor → target/);
  assert.match(vocal, /navigator\.mediaDevices\.getUserMedia/);
  assert.match(vocal, /source\.connect\(analyser\)/);
  assert.match(vocal, /getTracks\(\)\.forEach\(\(track\) => track\.stop\(\)\)/);
  assert.doesNotMatch(vocal, /MediaRecorder|localStorage|sessionStorage|fetch\(/);
  assert.match(vocal, /className="piano-voice-rail" role="img" aria-label=\{visualSummary\}/);
  assert.match(vocal, /<b style=\{\{ left: `\$\{railPosition \* 100\}%` \}\} \/>/);
  assert.doesNotMatch(vocal, /--voice-position/);
  assert.match(vocal, /className="piano-voice-spectrum-plot" role="img" aria-label=\{spectrumSummary\}/);
  assert.match(vocal, /<canvas ref=\{spectrumCanvasRef\} aria-hidden="true" \/>/);
  assert.match(vocal, /Voice energy × target harmonics/);
  assert.match(vocal, /ideal target harmonics/);
  assert.match(vocal, /Formants can make an upper harmonic taller/);
  assert.match(vocal, /no recording · no upload/);
  assert.match(vocal, /not measured piano audio/);
  assert.match(vocal, /not vocal quality, correctness, timbre, harmony, emotion/);
  assert.match(vocalModel, /export function detectVocalFundamental/);
  assert.match(vocalModel, /export function matchVocalPitch/);
  assert.match(vocalModel, /export function vocalTargetRailPosition/);
  assert.match(vocalModel, /returns null for a[\s\S]*weak or insufficiently periodic window/);
  assert.match(vocalSpectrumModel, /export function vocalSpectrumPosition/);
  assert.match(vocalSpectrumModel, /export function vocalTargetHarmonics/);
  assert.match(css, /\.piano-voice-source select/);
  assert.match(css, /\.piano-voice-spectrum-guides i \{ border-left: 1px dashed/);
  assert.match(css, /\.piano-voice-spectrum-guides b \{ border-left: 2px solid/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.piano-immersion-intro/);
  assert.match(css, /\.piano-research-layout-controls \{[^}]*grid-template-columns: repeat\(3/);
  assert.match(css, /\.piano-research-lattice \{[^}]*grid-template-columns: repeat\(4/);
  assert.match(css, /\.piano-research-matrix \{[^}]*table-layout: fixed/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.piano-research-clock-layout \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-research-boundaries \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-research-clock-node\.is-latest circle/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.piano-voice-reading \{ grid-template-columns: 1fr 1fr/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.voice-lab-reference \{ grid-template-columns: 1fr 1fr/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.piano-route-selector \{ grid-template-columns: 1fr 1fr/);
  assert.match(css, /\.piano-do-capture button\[aria-pressed="true"\]/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.piano-immersion-edge-hud[\s\S]*position: relative/);
  assert.match(css, /\.piano-immersion-lens\.is-scale \{[\s\S]*grid-column: 3;[\s\S]*grid-row: 3/);
  assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.piano-immersion-lens\.is-scale \{ grid-column: 2; grid-row: 2/);
  assert.match(css, /\.piano-immersion-scale-grid \{[\s\S]*grid-template-columns: repeat\(12/);
  assert.match(css, /\.piano-immersion-scale-grid > span\.is-latest b/);
  assert.match(css, /\.piano-immersion-scale-grid > span\.is-active/);
  assert.match(css, /\.piano-immersion-scale-actions \{[\s\S]*pointer-events: auto/);
  assert.match(css, /\.piano-immersion-scale-actions button\[aria-pressed="true"\]/);
  assert.match(css, /\.piano-immersion-scale-fingering ol \{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(22px, 1fr\)\)/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-immersion-scale-fingering/);
  assert.match(css, /\.piano-immersion-fingering \.is-finger-marker circle/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-immersion-reading \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-voice-controls,[\s\S]*\.piano-voice-reading/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.voice-lab-reference,[\s\S]*\.piano-voice-input \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-route-methods ol \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-immersion-edge-hud \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-immersion-lens\.is-scale \{ grid-column: 1; grid-row: auto/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.piano-immersion-interval-context-bar > div \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-immersion-stage \* \{ filter: none/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-voice-rail b/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-voice-spectrum-guides i/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-route-selector select/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-do-capture button\[aria-pressed="true"\]/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-immersion-character \.is-roughness \{ stroke-dasharray/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-immersion-latest-transition\.is-down[\s\S]*border-left-style: dashed/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-immersion-meter-controls input/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.piano-immersion-map-key i/);
  assert.match(css, /\.piano-immersion-note \.cosmos-node\.is-outside-route[\s\S]*stroke-dasharray/);
  assert.match(css, /\.immersion-pedal-ring[\s\S]*stroke-dasharray/);
  assert.match(css, /\.piano-immersion-stage \{[^}]*contain: layout paint/);
});

test("dynamic visuals and status changes expose nonvisual descriptions", async () => {
  const [ratio, scale, piano, ear, harmony, rhythm, recording, journey, atlas, personal] = await Promise.all([
    readFile(new URL("../app/RatioLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/ScaleLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PianoLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/EarLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/HarmonyLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RhythmLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RecordingLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/JourneyLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/AtlasLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PersonalLab.tsx", import.meta.url), "utf8"),
  ]);
  assert.match(ratio, /<canvas[^>]+role="img"[^>]+aria-label=/);
  assert.match(scale, /name="scale-degree"/);
  assert.match(scale, /aria-live="polite"/);
  assert.match(scale, /<ol className="step-fingerprint"/);
  assert.match(scale, /aria-labelledby="degree-field-title"/);
  assert.match(scale, /aria-controls="degree-field-reading"/);
  assert.match(scale, /className="degree-stack-plot"[\s\S]*role="img"[\s\S]*aria-label=/);
  assert.match(scale, /className="sr-only degree-field-live-summary"[\s\S]*aria-live="polite"[\s\S]*aria-atomic="true"/);
  assert.match(piano, /aria-label="Silent two-octave on-screen piano/);
  assert.match(piano, /aria-live="polite"/);
  assert.match(piano, /Grand staff showing/);
  assert.match(piano, /Evidence traces across/);
  assert.match(piano, /Choose movable Do around the circle of fifths/);
  assert.match(piano, /Repeated fifths morphing from a nonclosing pure-ratio spiral/);
  assert.match(piano, /id="hud-fifths-stack"/);
  assert.match(piano, /id="hud-fifths-temper"/);
  assert.match(piano, /Select an event across every view/);
  assert.match(piano, /Chord gestures grouped by attack timing/);
  assert.match(piano, /aria-label="Selected chord evidence"/);
  assert.match(piano, /aria-labelledby="hud-chord-semitone-atlas-title"/);
  assert.match(piano, /Root-position examples begin at/);
  assert.match(piano, /every card shares one logarithmic Hz axis and shows \{partialScopeCopy\}/);
  assert.match(piano, /Major and minor share the same unordered pair sizes/);
  assert.match(piano, /Read the arrows as available one-voice moves among these three types, not as forces/);
  assert.match(piano, /bass \+1 st → diminished rooted above/);
  assert.match(piano, /Chord type alone does not choose up, down, or rest/);
  assert.match(piano, /chordCrunchReading = selectedChordMeasure\?\.crunch \?\? liveHeldPerception\?\.roughness/);
  assert.match(piano, /aria-label="Correct inherited chord membership"/);
  assert.match(piano, /Restore.*Exclude.*inherited/);
  assert.match(piano, /id="hud-chord-window"/);
  assert.match(piano, /aria-label="Guided ascending scale walk"/);
  assert.match(piano, /aria-label="Performed scale fingerprint builder"/);
  assert.match(piano, /aria-label="Scale landing mutation comparison"/);
  assert.match(piano, />Change one landing<\/button>/);
  assert.match(piano, /Change one landing, keep the octave/);
  assert.match(piano, /aria-label="Choose one consequence of the moved scale landing"/);
  assert.match(piano, />Every connected interval<\/button>/);
  assert.match(piano, /hud-scale-ripple-summary" role="img" aria-label=\{summary\}/);
  assert.match(piano, /Global consequence/);
  assert.match(piano, /hud-scale-ripple-reading" role="status" aria-live="polite"/);
  assert.match(piano, /aria-label="Assumed spectral consequence of one changed interval"/);
  assert.match(piano, /hud-scale-spectrum-summary" role="img" aria-label=\{summary\}/);
  assert.match(piano, /hud-scale-spectrum-reading" role="status" aria-live="polite"/);
  assert.match(piano, /MIDI contains no instrument spectrum/);
  assert.match(piano, /hud-scale-mutation-reading[\s\S]*role="status" aria-live="polite"/);
  assert.match(piano, /`Δ\$\{signed\(delta\)\}`/);
  assert.match(piano, /More than one landing moved, so no single-position explanation is justified/);
  assert.match(piano, /aria-label="Choose one scale experiment"/);
  assert.match(piano, /silent performed fingerprint target/);
  assert.match(piano, /aria-label="Tonal gravity counterfactual microscope"/);
  assert.match(piano, /aria-label="Counterfactual evidence separation"/);
  assert.match(piano, /aria-labelledby="hud-phrase-compare-entry-title"/);
  assert.match(piano, /aria-label="Choose one phrase change to investigate"/);
  assert.match(piano, /aria-label="Five separate phrase comparison lenses"/);
  assert.match(piano, /aria-labelledby="hud-partial-title"/);
  assert.match(piano, /role="img" aria-label=\{summary\}/);
  assert.match(piano, /role="img" aria-label=\{comparisonSummary\}/);
  assert.match(piano, /aria-label="Five separate lenses for the selected attack change"/);
  assert.match(piano, /hud-last-attack-reading[\s\S]*role="status" aria-live="polite"/);
  assert.match(piano, /hud-phrase-change-status" role="status" aria-live="polite"/);
  assert.match(piano, /aria-label="Ending relationship ripple"/);
  assert.match(piano, /hud-ending-ripple-summary" role="img" aria-label=\{summary\}/);
  assert.match(piano, /Trace every ending relationship/);
  assert.match(piano, /hud-ending-ripple-reading" role="status" aria-live="polite"/);
  assert.match(piano, /role="group" aria-label=\{row\.label\}/);
  assert.match(piano, /role="status" aria-live="polite"/);
  assert.match(piano, /silent guided scale-walk target/);
  assert.match(piano, /aria-labelledby="hud-sonority-title"/);
  assert.match(piano, /aria-label="Separate conditional affordance changes"/);
  assert.match(piano, /silent controlled sonority reference/);
  assert.match(piano, /aria-label="Original versus one-key path comparison across five lenses"/);
  assert.match(piano, /aria-label="Report which landmark path felt more directed"/);
  assert.match(piano, /aria-label="Motion learning question"/);
  assert.match(piano, /Show what survived/);
  assert.match(piano, /aria-controls="hud-motif-fingerprint-detail"/);
  assert.match(piano, /hud-motif-fingerprint-grid" role="img" aria-label=\{summary\}/);
  assert.match(piano, /Set each statement’s first key to 0/);
  assert.match(piano, /does not infer intended motif, formal function, emotion, quality, or correctness/);
  assert.match(piano, /aria-labelledby="hud-motif-echo-title"/);
  assert.match(piano, /aria-label="Choose motif source length"/);
  assert.match(piano, /Freeze last 3/);
  assert.match(piano, /No smaller sub-match can replace your chosen boundary/);
  assert.match(piano, /Every chosen attack entered this comparison/);
  assert.match(piano, /Local sequence · source → change → return/);
  assert.match(piano, /The variation is open—try bringing the relationship back/);
  assert.match(piano, /not a detected section, theme, compositional intention, style, listener recognition, or quality judgment/);
  assert.match(piano, /Did the last statement feel like a return to you\?/);
  assert.match(piano, /aria-label="Modeled relationship and listener report kept separate"/);
  assert.match(piano, /aria-label="Report whether the last statement felt like a return"/);
  assert.match(piano, /Agreement with the relationship detector is not a goal/);
  assert.match(piano, /Your report does not turn that relationship into detected form, universal recognition, emotion, correctness, or musical quality/);
  assert.match(piano, /Particular performances · no average/);
  assert.match(piano, /Did moving the relationship change your experience\?/);
  assert.match(piano, /They do not establish your recognition threshold or a general law about transposition/);
  assert.match(piano, />Reflect on the whole arc<\/button>/);
  assert.match(piano, /motifReturnArcEventIds\(session\.sourceEvents\.map/);
  assert.match(piano, /The source aged out of the sixty-second phrase\. Start a new arc to reflect on its exact timing/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("motif-return", specimen\)/);
  assert.match(piano, /prompt\s*\.replace\("this phrase", "this source–variation–return arc"\)/);
  assert.match(piano, /replace\("this relationship path", "this source–variation–return arc"\)/);
  assert.match(piano, /replace\("this particular experience", "this source–variation–return experience"\)/);
  assert.match(piano, /origin === "motif-return" \? "motif source \+ variation \+ return"/);
  assert.match(piano, /The exact source, latest variation, and relationship return are frozen together/);
  assert.match(piano, /Save this return-arc report/);
  assert.match(piano, />Reflect on performed path<\/button>/);
  assert.match(piano, /How did this whole performed route feel\?/);
  assert.match(piano, /landmarkPerformanceEventIds\(landmarkPerformanceCapture\.fieldEventIds, landmarkPath\.steps\.length\)/);
  assert.match(piano, /Every exact attack used to complete this generated path is frozen in its original chronology/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("landmark-path", specimen/);
  assert.match(piano, /Save this landmark-path report/);
  assert.match(piano, /this performed landmark path/);
  assert.match(piano, /relationship fingerprint · Do factored out/);
  assert.match(piano, /The whole route inside one octave/);
  assert.match(piano, /className="hud-landmark-fingerprint-plot"[\s\S]*role="img" aria-label=\{summary\}/);
  assert.match(piano, /aria-label="Select one transition to inspect what changed"/);
  assert.match(piano, /aria-pressed=\{selectedTransitionIndex === transition\.toStepIndex\}/);
  assert.match(piano, /What did field \{change\.toField\.stepIndex \+ 1\} change\?/);
  assert.match(piano, /className="hud-landmark-change-plot"[\s\S]*role="img" aria-label=\{summary\}/);
  assert.match(piano, /aria-label="Five evidence lenses for the selected route transition"/);
  assert.match(piano, /Sound · authored \+ modeled/);
  assert.match(piano, /Experience · yours/);
  assert.match(piano, /no other lane supplies this answer/);
  assert.match(piano, /timing, velocity, releases, pedal, balance, actual instrument spectrum, fingering, intention, emotion, and musical goodness remain outside it/i);
  assert.match(piano, /Transposing the whole route leaves this folded pattern unchanged/);
  assert.match(piano, /register, timing, the assumed sound, tonal interpretation, and your experience remain separate evidence/i);
  assert.match(piano, /Which underlying route property changes\?/);
  assert.match(piano, /route A held · now perform B/);
  assert.match(piano, /function isLandmarkRouteCompareSession/);
  assert.match(piano, /session\.sourcePathId !== session\.targetPathId/);
  assert.match(piano, /version: 25[\s\S]*landmarkRouteCompareSession/);
  assert.match(piano, /Two routes in the same underlying coordinate/);
  assert.match(piano, /className="hud-landmark-compare-plot"[\s\S]*role="img" aria-label=\{summary\}/);
  assert.match(piano, /role="table" aria-label="Route structure comparison"/);
  assert.match(piano, /Dashed capsules mark exact field shapes present in both routes/);
  assert.match(piano, /It is not a style match/);
  assert.match(piano, /Timing, articulation, register, actual sound, tonal hearing, emotional response, familiarity, and goodness remain separate evidence/);
  assert.match(personal, /Latest performed landmark:/);
  assert.match(personal, /latestLandmarkCharacterContrast\(phraseObservations\)/);
  assert.match(personal, /What changed when you played this route again\?/);
  assert.match(personal, /aria-label="Four listener reports shown separately"/);
  assert.match(personal, /aria-label="Measured MIDI and modeled teaching evidence kept separate"/);
  assert.match(personal, /The reports and evidence are aligned, not causally joined/);
  assert.match(piano, /aria-labelledby="hud-pulse-title"/);
  assert.match(piano, /Later MIDI attack clusters placed against the learner’s four-tap pulse/);
  assert.match(piano, /aria-labelledby="hud-phrase-breath-title"/);
  assert.match(piano, /Mark a candidate break after/);
  assert.match(piano, /Performed pitch path divided only at long onset-group gaps containing release-proven silence/);
  assert.match(piano, /hud-breath-reading" role="status" aria-live="polite"/);
  assert.match(piano, /Unknown releases, overlaps, and merely long held notes never become quiet-space boundaries/);
  assert.match(piano, /does not detect intended phrasing, breath, meter, form, expressiveness, correctness, or musical goodness/);
  assert.match(piano, />Compare one pause<\/button>/);
  assert.match(piano, /onComparePause=\{\(\) => beginPhraseCompare\("timing"\)\}/);
  assert.match(piano, /modeled crunch/);
  assert.match(piano, /MIDI contains no acoustic roughness measurement/);
  assert.match(ear, /aria-labelledby="live-ear-title"/);
  assert.match(ear, /role="img" aria-label=\{summary\}/);
  assert.match(ear, /aria-label="Five separate lenses for this interval and its assumed sounds"/);
  assert.match(ear, /<details className="ear-authoring-disclosure"/);
  assert.match(harmony, /aria-labelledby="live-harmony-title"/);
  assert.match(harmony, /role="img" aria-label=\{accessibleSummary\}/);
  assert.match(harmony, /aria-label="Five separate evidence lenses for the chord change"/);
  assert.match(harmony, /<details className="harmony-authoring-disclosure"/);
  assert.match(rhythm, /aria-labelledby="rhythm-live-title"/);
  assert.match(rhythm, /role="img"/);
  assert.match(rhythm, /Pitchless timing profile with/);
  assert.match(rhythm, /<details className="rhythm-authoring-disclosure"/);
  assert.match(recording, /aria-live="polite"/);
  assert.match(journey, /role="img" aria-label=/);
  assert.match(journey, /aria-labelledby="journey-live-title"/);
  assert.match(journey, /Piece-local expectation trail/);
  assert.match(journey, /<details className="journey-generated-disclosure"/);
  assert.match(atlas, /aria-label=\{`Music landmarks positioned/);
});

test("scale generator keeps orbit, window, home, and bounded meaning accessible", async () => {
  const [generator, model, css] = await Promise.all([
    readFile(new URL("../app/ScaleGeneratorExplainer.tsx", import.meta.url), "utf8"),
    readFile(new URL("../lib/scale-generator-model.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(generator, /<section className="scale-lesson generator-lesson" aria-labelledby="generator-lesson-title">/);
  assert.match(generator, /The fifth is not sharpened\. The fifth becomes home/);
  assert.match(generator, /role="group" aria-label="Circle of fifths major-scale derivation stages"/);
  assert.match(generator, /aria-controls="generator-derivation-reading"/);
  assert.match(generator, /className="sr-only generator-derivation-live-summary" role="status" aria-live="polite" aria-atomic="true"/);
  assert.match(generator, /className="generator-degree-rail" role="img" aria-label=/);
  assert.match(generator, /className="fifths-window-comparison" role="img" aria-label=/);
  assert.match(generator, /<fieldset className="generator-options">/);
  assert.match(generator, /id="generator-window-size" type="range"/);
  assert.match(generator, /className="generator-clock" role="img" aria-label=\{description\}/);
  assert.match(generator, /className="sr-only generator-workbench-live-summary" role="status" aria-live="polite" aria-atomic="true"/);
  assert.match(generator, /The full \+7 orbit is chromatic; major appears only after selecting a seven-stop window and where Do sits/);
  assert.match(generator, /Transposition always preserves the shape\. One-out\/one-in membership does not/);
  assert.match(generator, /Contingent at the boundary; exact inside it/);
  assert.match(generator, /tonic detection · function · resolution · consonance · emotion · quality/);
  assert.match(generator, /Pure 3:2 spiral/);
  assert.match(model, /cycleLength = divisions \/ divisor/);
  assert.match(model, /boundaryRemainder: normalizePitchClass\(count \* orbit\.generator, divisions\)/);
  assert.match(css, /@media \(max-width: 680px\)[\s\S]*\.generator-stability-ledger,[\s\S]*\.generator-boundary-grid \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 380px\)[\s\S]*\.generator-degree-rail \{ grid-template-columns: repeat\(4/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.generator-clock g\.is-leaving circle/);
  assert.match(css, /\.generator-gap-strip > li \{[^}]*flex-basis: 0/);
  assert.match(css, /\.generator-options button:nth-of-type\(4n\)/);
  assert.match(css, /\.generator-comparison-table \.generator-table-head \{ position: absolute; width: 1px/);
  assert.doesNotMatch(generator, /tabIndex=\{?[1-9]/);
});

test("focus, reduced-motion, and non-color contracts are present", async () => {
  const [css, ratio, scale, piano, ear, harmony, rhythm, journey] = await Promise.all([
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/RatioLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/ScaleLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/PianoLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/EarLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/HarmonyLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RhythmLab.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/JourneyLab.tsx", import.meta.url), "utf8"),
  ]);
  assert.match(css, /select:focus-visible/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
  assert.match(css, /animation-duration: 0\.01ms !important/);
  assert.match(css, /cloud-blues[\s\S]*border-style: dotted/);
  assert.match(css, /cloud-classical[\s\S]*border-style: double/);
  assert.match(css, /\.atlas-point[\s\S]*width: max\(50px, var\(--point-size\)\)/);
  assert.match(css, /\.personal-landmark-axis > i b,[\s\S]*border-radius: 50%/);
  assert.match(css, /\.personal-landmark-axis > i em[\s\S]*transform: rotate\(45deg\)/);
  assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.personal-landmark-pair \{ grid-template-columns: 1fr; \}/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.personal-landmark-axis > i em \{ border-color: Highlight/);
  assert.match(css, /\.hud-landmark-fingerprint-node\.is-root[\s\S]*\.hud-landmark-fingerprint-node\.is-changed/);
  assert.match(css, /\.hud-landmark-fingerprint-held[\s\S]*stroke: var\(--piano-blue\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-landmark-fingerprint-transitions \{ grid-template-columns: 1fr; \}/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-landmark-fingerprint-node\.is-changed \{ fill: Highlight/);
  assert.match(css, /\.hud-landmark-change-lenses[\s\S]*grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-landmark-change-lenses \{ grid-template-columns: 1fr; \}/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-landmark-change-node\.is-after \{ fill: LinkText/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.degree-field-degree-grid button\[aria-pressed="true"\]/);
  assert.match(css, /@media \(max-width: 380px\)[\s\S]*\.degree-field-degree-grid \{ grid-template-columns: repeat\(3/);
  assert.match(css, /\.hud-landmark-compare-field > rect:first-child[\s\S]*stroke-dasharray: 3 3/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-landmark-compare-table > div \{ grid-template-columns: 1fr 1fr; \}/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-landmark-compare-field > rect:first-child \{ stroke: Highlight/);
  assert.match(css, /\.lab-nav-primary[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(ratio, /<details className="lab-nav-more"/);
  assert.match(ratio, /aria-label="Live piano phrase available"/);
  assert.match(ratio, /matchMedia\("\(prefers-reduced-motion: reduce\)"\)/);
  assert.match(ratio, /behavior: prefersReducedMotion \? "auto" : "smooth"/);
  assert.match(ratio, /className="skip-link" href="#lab-stage" onClick=\{skipToActiveLab\}/);
  assert.match(ratio, /id="lab-stage" className="lab-stage" tabIndex=\{-1\}/);
  assert.match(css, /@media \(forced-colors: active\)/);
  assert.match(css, /\.atlas-point\.is-selected > i[\s\S]*outline: 4px solid Highlight/);
  assert.match(css, /\.spectrum-partial\.voice-6[\s\S]*border: 3px double Canvas/);
  assert.match(css, /\.learning-scale \.step-fingerprint > li span/);
  assert.doesNotMatch(ratio, /tabIndex=\{?[1-9]/);
  assert.doesNotMatch(scale, /className="degree-inspector"[^>]*aria-live/);
  assert.doesNotMatch(piano, /tabIndex=\{?[1-9]/);
  assert.match(css, /\.piano-key\.is-circle-target/);
  assert.match(css, /\.piano-key\.is-scale-walk-target/);
  assert.match(css, /\.piano-key\.is-scale-builder-target/);
  assert.match(css, /\.hud-gravity-counterfactual-chart > span\.is-target/);
  assert.match(css, /\.hud-gravity-counterfactual-chart i\.is-before[\s\S]*LinkText/);
  assert.match(css, /\.hud-phrase-lens-profile > article\.is-invariant[\s\S]*border-left/);
  assert.match(css, /\.hud-phrase-change-reading\.has-target[\s\S]*LinkText/);
  assert.match(css, /\.hud-phrase-change-reading > button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-ending-ripple-spoke \.is-attempt i b[\s\S]*border: 1px dashed/);
  assert.match(css, /\.hud-ending-ripple-reading \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-motif-fingerprint-entry button\[aria-expanded="true"\]/);
  assert.match(css, /\.hud-motif-time-bar i[\s\S]*flex: var\(--motif-gap-share\)/);
  assert.match(css, /\.hud-motif-fingerprint-grid \{ grid-template-columns: minmax\(76px/);
  assert.match(css, /\.hud-motif-echo-start \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-return-trail ol \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-return-trail li\.is-variation[\s\S]*border-top-style: dashed/);
  assert.match(css, /\.hud-motif-return-trail li\.is-return[\s\S]*border-top-style: double/);
  assert.match(css, /\.hud-motif-return-trail li\.is-return \{ border-top-color: LinkText/);
  assert.match(css, /\.hud-motif-experience-options button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-motif-experience-options \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-experience-options button\[aria-pressed="true"\][\s\S]*HighlightText/);
  assert.match(css, /\.hud-motif-return-contrast li\.is-shifted[\s\S]*border-top-style: dashed/);
  assert.match(css, /\.hud-motif-return-contrast ol \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-motif-return-contrast li\.is-shifted \{ border-top-color: LinkText/);
  assert.match(css, /\.hud-motif-echo button \{ color: ButtonText/);
  assert.match(css, /\.hud-partial-link\.is-aligned[\s\S]*LinkText/);
  assert.match(css, /\.hud-partial-link\.is-interaction[\s\S]*Highlight/);
  assert.match(css, /\.hud-echo-span\.is-source[\s\S]*LinkText/);
  assert.match(css, /\.hud-echo-span\.is-attempt[\s\S]*Highlight/);
  assert.match(css, /\.hud-scale-mutation-routes \.is-source \.is-present i[\s\S]*border-radius: 50%/);
  assert.match(css, /\.hud-scale-mutation-routes \.is-attempt \.is-present i[\s\S]*border-style: dashed/);
  assert.match(css, /\.hud-scale-mutation-routes \.is-present\.is-changed i[\s\S]*border: 3px double/);
  assert.match(css, /\.hud-scale-mutation-gaps \{ grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.hud-scale-mutation-reading \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-scale-mutation-view button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-scale-ripple-spoke \.is-attempt i b[\s\S]*border: 1px dashed/);
  assert.match(css, /\.hud-scale-ripple-spoke \.is-attempt i b[\s\S]*border-color: Highlight/);
  assert.match(css, /\.hud-scale-ripple-reading \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-scale-ripple-spoke\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-scale-spectrum-partial\.is-upper[\s\S]*stroke-dasharray/);
  assert.match(css, /\.hud-scale-spectrum-interaction[\s\S]*fill: var\(--piano-gold\)/);
  assert.match(css, /\.hud-scale-spectrum-reading \{ border-left-color: LinkText/);
  assert.match(piano, /aria-label="Interval context lesson"/);
  assert.match(piano, /aria-label="Five separate lenses for the source and echoed interval"/);
  assert.match(piano, />Reflect on source \+ echo<\/button>/);
  assert.match(piano, /origin === "interval-echo" \? "interval source \+ echo"/);
  assert.match(piano, /replace\("this phrase", "this source-and-echo comparison"\)/);
  assert.match(piano, /"Use whole live phrase"/);
  assert.match(piano, /aria-label="Five separate lenses for the selected chord change"/);
  assert.match(piano, />Reflect on chord change<\/button>/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("chord-change", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this chord change"\)/);
  assert.match(piano, /aria-label="Choose one chord-learning question"/);
  assert.match(piano, /aria-label="Five separate lenses for the source chord and new voicing"/);
  assert.match(piano, /<svg className="hud-chord-echo-figure"[\s\S]*role="img"/);
  assert.match(piano, />Freeze this relationship<\/button>/);
  assert.match(piano, />Reflect on source \+ voicing<\/button>/);
  assert.match(piano, /What remains if register, doubling, and starting pitch disappear\?/);
  assert.match(piano, /Fold into one octave/);
  assert.match(piano, /How did changing one position reshape the chord\?/);
  assert.match(piano, /Compare changed gaps/);
  assert.match(piano, /Delta labels show exactly which adjacent gaps gained or lost space/);
  assert.match(piano, /both closed loops still total 12/);
  assert.match(piano, /aria-pressed=\{octaveFoldRevealed\}/);
  assert.match(piano, /<svg className="hud-chord-fold-figure"[\s\S]*role="img"/);
  assert.match(piano, /comparison start is a canonical rotation, not a chord root or movable Do/);
  assert.match(piano, /This display-only view changes no MIDI, frequency, voicing, model, or listener report/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("chord-voicing-echo", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this source-and-revoicing comparison"\)/);
  assert.match(piano, /sourceEvents: saved\.chordVoicingEchoSession\.sourceEvents\.map/);
  assert.match(piano, /aria-label="Five separate lenses for the source and replayed chord move"/);
  assert.match(piano, /<svg className="hud-chord-motion-figure"[\s\S]*role="img"/);
  assert.match(piano, />Freeze this two-chord move<\/button>/);
  assert.match(piano, />Reflect on source \+ replayed move<\/button>/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("chord-motion-echo", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this source-and-replayed chord move"\)/);
  assert.match(piano, /sourceBeforeEvents: saved\.chordMotionEchoSession\.sourceBeforeEvents\.map/);
  assert.match(piano, /aria-label="Choose the replay's movable Do reference frame"/);
  assert.match(piano, />Does the tonal job travel when the reference frame travels\?</);
  assert.match(piano, />Keep Do fixed<\/button>/);
  assert.match(piano, />Move Do \{formatSemitones\(comparison\.transpositionSteps!, 0, true\)\}<\/button>/);
  assert.match(piano, /This is a display-only context counterfactual and never enters or sounds a note/);
  assert.match(piano, /replay Do moved \+ same route/);
  assert.match(piano, /restored the same relative-role path under this model; it did not prove the same heard function/);
  assert.match(piano, /The display-only Do counterfactual never supplies your report/);
  assert.match(piano, />What did this intended landing actually do\?</);
  assert.match(piano, /"Trace this landing"/);
  assert.match(piano, /aria-expanded=\{landingRevealed\}/);
  assert.match(piano, /aria-controls="hud-resolution-landing-panel"/);
  assert.match(piano, /<p className="sr-only" role="status" aria-live="polite">\{targetMatched/);
  assert.match(piano, /aria-label="Five separate lenses for the performed resolution landing"/);
  assert.match(piano, /The fork label named an intention, not a detected function or felt resolution/);
  assert.match(piano, /No lens proves that the fork resolved, caused a feeling, was stylistically correct, or was musically good/);
  assert.match(piano, /Pull is modeled distance still left before Do, so zero can mean arrival—not indifference/);
  assert.match(piano, /sourceEvent: \{ \.\.\.sourceEvent, fieldNotes: \[\.\.\.sourceEvent\.fieldNotes\] \}/);
  assert.match(piano, /!phraseEvents\.some\(\(event\) => event\.id === resolutionTarget\.sourceEvent!/);
  assert.match(piano, /holdBoundedExperienceSpecimen\("resolution-fork", specimen\)/);
  assert.match(piano, /prompt\.replace\("this phrase", "this intended landing in context"\)/);
  assert.match(piano, /aria-label="One-pause timing comparison"/);
  assert.match(piano, /Two performances of the same pitch path with one onset gap changed/);
  assert.match(piano, /hud-pause-reading" role="status" aria-live="polite"/);
  assert.match(piano, /"Trace the changed pause"/);
  assert.match(piano, /aria-expanded=\{pauseRevealed\}/);
  assert.match(piano, /aria-controls="hud-pause-mutation-detail"/);
  assert.match(piano, /Onset spacing and release-proven silence are separate/);
  assert.match(piano, /does not prove a phrase boundary, meter, expressive intention, emotion, preference, quality, or causal effect/);
  assert.match(piano, />Did the hands make the same time-shape\?</);
  assert.match(piano, /"Compare gesture timing"/);
  assert.match(piano, /aria-expanded=\{gestureTimingRevealed\}/);
  assert.match(piano, /aria-controls="hud-chord-gesture-detail"/);
  assert.match(piano, /<svg viewBox="0 0 720 150" role="img"/);
  assert.match(piano, /Missing releases remain unknown\. Velocity is an attack control, not measured acoustic loudness/);
  assert.match(piano, /does not infer meter, groove, intention, feeling, preference, or quality/);
  assert.match(piano, /sourceBeforeAttackEventIds: before\.gesture\.attacks\.map/);
  assert.match(piano, /version: 25/);
  assert.match(piano, /experienceOrigin === "phrase" \|\| experiencePhrase\.length < 3/);
  assert.match(piano, /landmarkLastMatchIdRef\.current = 0;\s+setExperienceOrigin\("phrase"\);\s+setExperienceContext\(null\);\s+setExperiencePhrase\(\[\]\);/);
  assert.match(piano, /<details className="hud-interval-tools">/);
  assert.match(piano, /Could these pitches nearly repeat inside one longer cycle\?/);
  assert.match(piano, />Find shared cycles<\/button>/);
  assert.match(piano, /role="img" aria-label=\{summary\}/);
  assert.match(piano, /Phases are reset together only for this visual comparison/);
  assert.match(piano, /Not a detected root, chord name, tonal function, acoustic fusion, consonance, emotion, or goodness/);
  assert.match(piano, /Reference-frequency height/);
  assert.match(piano, /Derived from MIDI key number at A4=440 Hz/);
  assert.match(piano, /pitch bend, instrument tuning, and audio pitch are not captured/);
  assert.match(piano, /Candidate shared periodicity · derived reference frequencies/);
  assert.match(ear, /MIDI supplies two key numbers and timing—not acoustic pitch or overtones/);
  assert.match(ear, /Pitch bend, instrument tuning, audio pitch, and your response are not captured/);
  assert.match(piano, /simultaneous partial-interaction comparison would answer the wrong question/);
  assert.match(css, /\.hud-echo-reading[\s\S]*grid-template-columns: repeat\(3/);
  assert.match(css, /\.hud-echo-experience button \{ justify-self: start/);
  assert.match(css, /\.hud-shared-cycle-choices button\[aria-pressed="true"\]/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-shared-cycle-reading \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-shared-cycle-voice path \{ stroke: LinkText/);
  assert.match(css, /\.hud-chord-change-lenses,[\s\S]*\.hud-chord-echo,[\s\S]*\.hud-chord-motion-echo \{ min-width: 0/);
  assert.match(css, /\.hud-chord-question-options button\[aria-pressed="true"\]/);
  assert.match(css, /\.hud-chord-echo-node\.is-source[\s\S]*LinkText/);
  assert.match(css, /\.hud-chord-fold-test > button\[aria-pressed="true"\][\s\S]*background: var\(--foreground\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-fold-test > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-fold-figure \.is-attempt \.hud-chord-fold-node[\s\S]*HighlightText/);
  assert.match(css, /\.hud-chord-fold-segment\.is-changed[\s\S]*stroke-dasharray: 2 2/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-fold-segment\.is-changed \{ stroke: Highlight/);
  assert.match(css, /\.hud-chord-motion-node\.is-source\.is-before[\s\S]*CanvasText/);
  assert.match(css, /\.hud-chord-motion-node\.is-attempt\.is-after[\s\S]*HighlightText/);
  assert.match(css, /\.hud-resolution-landing-node\.is-landing rect[\s\S]*var\(--piano-gold\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-resolution-feedback-actions button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-resolution-landing-node\.is-landing rect \{ fill: Highlight/);
  assert.match(css, /\.hud-pause-link \.is-attempt \{ stroke-dasharray/);
  assert.match(css, /\.hud-pause-link\.is-changed line[\s\S]*var\(--piano-gold\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-pause-entry > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-pause-link\.is-changed line,[\s\S]*stroke: Highlight/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-pause-node\.is-attempt rect \{ stroke: LinkText/);
  assert.match(css, /\.hud-chord-gesture-test > button\[aria-expanded="true"\]/);
  assert.match(css, /\.hud-chord-gesture-hold\.is-pedal[\s\S]*stroke-dasharray/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-gesture-test > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-gesture-attack\.is-after \{ fill: Highlight/);
  assert.match(css, /\.hud-chord-frame-options button\[aria-pressed="true"\][\s\S]*background: var\(--foreground\)/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-question-options \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-motion-actions button \{ width: 100%/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-chord-frame-options \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-chord-frame-options button\[aria-pressed="true"\][\s\S]*background: Highlight/);
  assert.match(css, /\.hud-last-lenses button:disabled/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-echo-reading \{ grid-template-columns: 1fr/);
  assert.match(css, /\.hud-last-attack-reading\.is-attributable[\s\S]*LinkText/);
  assert.match(css, /\.hud-last-lenses article\.is-modeled[\s\S]*Highlight/);
  assert.match(css, /\.hud-phrase-report-rows button\[aria-pressed="true"\][\s\S]*Highlight/);
  assert.match(css, /\.hud-landmark-counterfactual-report button\[aria-pressed="true"\][\s\S]*Highlight/);
  assert.match(css, /\.piano-key\.is-sonority-target/);
  assert.match(css, /\.hud-sonority-question\.has-change[\s\S]*border-left/);
  assert.match(css, /\.hud-pulse-status\.is-ready[\s\S]*border-left/);
  assert.match(css, /\.hud-pulse-onset[\s\S]*Highlight/);
  assert.match(css, /\.hud-breath-gate line[\s\S]*stroke-dasharray/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-motion-mode-nav button:last-child \{ grid-column: 1 \/ -1/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-breath-segments \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-breath-gate line \{ stroke: Highlight/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-breath-event circle \{ fill: Canvas; stroke: CanvasText/);
  assert.match(css, /@media \(max-width: 620px\)[\s\S]*\.hud-breath-next > button \{ width: 100%/);
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*\.hud-breath-next \{ border-left-color: LinkText/);
  assert.match(css, /\.hud-walk-route li\.is-current[\s\S]*box-shadow/);
  assert.match(css, /\.piano-key\.is-active,[\s\S]*Highlight/);
  assert.match(css, /\.rhythm-live-axis > span[\s\S]*background: LinkText/);
  assert.doesNotMatch(rhythm, /tabIndex=\{?[1-9]/);
  assert.match(css, /\.journey-live-thread > li\.is-known[\s\S]*border-color: LinkText/);
  assert.match(css, /\.journey-live-thread > li\.is-new[\s\S]*border-color: Highlight/);
  assert.match(css, /\.live-harmony-note\.is-previous[\s\S]*stroke: LinkText/);
  assert.match(css, /\.live-harmony-note\.is-current[\s\S]*fill: Highlight/);
  assert.match(css, /\.live-ear-roughness circle[\s\S]*stroke: Highlight/);
  assert.match(css, /\.live-ear-harmonicity rect[\s\S]*stroke: LinkText/);
  assert.match(css, /\.live-ear-fusion path[\s\S]*fill: Highlight/);
  assert.doesNotMatch(ear, /tabIndex=\{?[1-9]/);
  assert.doesNotMatch(harmony, /tabIndex=\{?[1-9]/);
  assert.doesNotMatch(journey, /tabIndex=\{?[1-9]/);
});
